# SITE CONFIGURATION
title: Translucent Green Plastic Press # your site title
author: Jonah Lubin # You :P
description: > # Meta description of Homepage
  Small press specializing in good books.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Beiträge', link: '/beitraege'}
tagline: >

hero_img: posts/banner.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: translucentgreenplasticpress@gmail.com # email for form submission

twitter_username: trnslucentgreen # replace with your_twitter_username or comment to remove link from footer
github_username:  sreyfe # replace with your_github_username or comment to remove link from footer

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

authors:
  maria:
    name: Maria Laurids Lazzarotti
    display_name: Maria
    img: /assets/img/avis/maria.jpg
    email: 
    web: 
    orcid:
    twitter:
    github: asdasd
    description: Maria (they/them) is a student in comparative literature in Berlin, an italian in exile, and God's favourite little soldier.